# Ruby のベースイメージを指定
FROM ruby:3.4.8

# 環境変数の設定
# 日本語対応
ENV LANG C.UTF-8
# タイムゾーンを日本に設定
ENV TZ Asia/Tokyo

# 必要なパッケージをインストール
# パッケージリストを更新 `-qq` = 余計なメッセージを表示しない。 `-y` = 確認なしでインストール。
RUN apt-get update -qq \
  && apt-get install -y curl \
  && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && apt-get update -qq \
  && apt-get install -y build-essential libpq-dev nodejs \
  && npm install -g yarn

# libvipsバイナリをインストール
RUN apt-get update && \
    apt-get install -y libvips42 libvips-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# アプリケーションディレクトリの作成
RUN mkdir /myapp
# 作業ディレクトリを設定
WORKDIR /myapp

# Bundlerのインストール
RUN gem install bundler:2.3.17

# GemfileとGemfile.lockをコピーして、必要なgemをインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# package.jsonの依存関係をインストール
COPY package.json yarn.lock ./
RUN yarn install

# アプリケーションのコードをコピー
COPY . /myapp
